### ISSUE TITLE
Battery saver on OnePlus/Huawei and other OEMs may kill Koronavilkku

### ISSUE THREAD

**Issue by kypeli** [THLfi/koronavilkku-android#31]
It seems that the battery saver functionality on at least OnePlus Nord and OnePlus 7 Pro phones may kill/disable Koronavilkku. I mean, when launching Koronavilkku in the morning, it says that it's disabled, although it was active before going to bed.

This might be due to the battery optimization feature on the phones. I understand that the app developers might not be able to control this behaviour. But I would encourage THL/Solita to add some documentation and instructions about this harmful functionality in those phones that the users do not think that Koronavilkku is active on the phones when in fact it might not be.

The solution to this would be to disable battery optimization for Koronavilkku in the app's settings from Settings -> Apps & Notifications -> Koronavilkku -> Advanced -> Battery optimization and select "Do not optimize".

**Comment by skvark** [comment]
Probably true also for many other mobile phone brands, see https://dontkillmyapp.com/ for more info.

**Comment by dalathegreat** [comment]
I also noticed this on my Huawei P20. Android "optimizes" this and kills the app.

**Comment by kypeli** [comment]
Yes, good points. I updated the title accordingly.

**Comment by finmackandal** [comment]
I used a Swiss equivalent to this app, and it asks permission or recommend as apart of the setup process (next->next approach) to disable battery optimization and maybe related stuff (background permission maybe?).

could be possible to do something like this for this app?

I have a Samsung A51 and installed the app 31 August.

Last weekend I read the "Exposure checks" because I'm curious, and there was only one entry:
03.09

After that I changed the battery optimization by hand:
Now I see two additional entries:
07.09
09.09

is two days the expected "exposure check" periods?

A lay man setup for disable every optimization that could prevent the app running properly would be nice.

**Comment by solita-jussihei** [comment]
Latest app version 1.0.2 adds a prompt to disable battery optimization for the app in device settings.

Some device manufacturers, like OnePlus, Huawei and Xiaomi, have added their own power saver functionality to Android that we unfortunately cannot control/request from the app, so @kypeli you're right it would be a good idea to have instructions for these cases.
