### ISSUE TITLE
No notification to user even though app isn't working

### ISSUE THREAD

**Issue by mikahe** [THLfi/koronavilkku-android#4]
Due to "fi.thl.koronahaavi.sim.debug E/DiagnosisKeyUpdateWorker: Failed to download diagnosis keys"
app is in useless state (also emulator BT off). However, user is completely unaware of this.

How about real user error and problems, such as user turning off Bluetooth and not turning it back on for extended period of time etc. failure scenarios?

**Comment by solita-jussihei** [comment]
Thanks for the suggestion! We have considered showing information about a failed backend update, and will evaluate if it might be included in later releases. A single failure of the periodic update task (like the one your log entry shows) is not critical to app functionality, since the operating system continues to broadcast and collect random device identifiers via bluetooth regardless of our update task. (Note that you would need to run the app in liveDebug build variant to use the actual OS exposure notifications module, but that is restricted to specific signed apps and would not work on emulator)

If the device is offline for a long period of time, or network connection continues to fail for some other reason, it would be useful to see that status in the app.

If user turns off bluetooth, the operating system shows a notification and app home screen status is updated, and a function shown in the app to turn system back on (which automatically turns on bluetooth).

**Comment by denzilferreira** [comment]
This should be addressed in the latest version as we should the last time the data was last checked and updated? @solita-jussihei

**Comment by solita-jussihei** [comment]
Yes you're right, thanks @denzilferreira, even though we won't send a notification about it, the user can see in app home screen if updates not done for 24hrs
