### ISSUE TITLE
Clarification with google reported "Exposure Notifications"->"Exposure Checks"

### ISSUE THREAD

**Issue by entibaldi** [THLfi/koronavilkku-android#48]
Hello,

I'd like a clarification on the data reported by google if user goes to Settings->Google->COVID-19 Exposure Notifications -> Exposure Checks.

Google claims the data "shows requests made by apps to check for potential exposure to COVID-19 over the past 14 days".
Besides from the apparently completely random order the data is presented, there seem to be a daily exposure check happening. Every day there are a certain "Number of keys". "Number of matches" (I guess if there was a corona contact),  and a "Hash". What does this data exactly mean?

I'm curious because I compared my phone and my wife's and we have exactly the same number of keys shared day after day, and the same hashes day after day. We obviously spend our days also in separate places and have contact with different people, so is there a reason why these numbers are the same day after day?

**Comment by solita-jussihei** [comment]
Hi, thanks for asking, I understand how this might be confusing. The data reported by Google in device settings shows when the app has downloaded keys of other Koronavilkku users that have reported a positive diagnosis. Note that these are downloaded from system backend, not scanned by your device, and they are daily rotating keys, which means the count is not the same as number of people/app users.

These keys are then provided to the local Google exposure notification system on your device, to check if you've been in contact with these keys. That's why Google calls these "checks". Thats also why your wife's phone shows the same number of keys, because these same keys are downloaded by all app users.

**Comment by entibaldi** [comment]
@solita-jussihei thank you for the answer, it is clear now! I'll close this
