### ISSUE TITLE
Add koronavilkku to F-Droid/samsung store/amazon store/direct apk

### ISSUE THREAD

**Issue by tatusamma** [THLfi/koronavilkku-android#76]
Hi,

I see that last request to add Koronavilkku to F-Droid was closed today and I just find it sad for a project which has been funded by all of us is such restricted as it is. While I understand technical restrictions for the API, I don't consider the issue as closed or resolved.

I think we could have good and insightful discussion on this topic somewhere, but you closed the only place where to follow this discussion. What was the THL's view on this: is there any chance getting Koronavilkku from any other store apart from Google's Play store?

**Comment by spheroid** [comment]
The application requires either Google Play Services or Huawei Mobile Services in order to function and therefore it is not distributed through other app stores. Apparently you can also build the source code yourself and substitute the Google Play Services dependency with microG implementation, but we're not going to officially support this for the time being.
